services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      API_GATEWAY_PORT: ${API_GATEWAY_PORT}
      RATE_LIMIT_REQUESTS_PER_SECOND: ${RATE_LIMIT_REQUESTS_PER_SECOND}
      UPSTREAM_SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - ${API_GATEWAY_PORT}:80
      
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    command: ["redis-server", "--loglevel", "verbose"]

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on: [db]
  #   environment: 
  #     RACK_ENV: ${RACK_ENV}
  #     SERVER_PORT: ${SERVER_PORT}
    
volumes:
  postgres_data: